// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// Plain `import "dotenv/config"` only loads `.env` by default, which here holds
// a stray Prisma-Postgres URL from `prisma init`'s scaffold — not the real
// Neon database (pulled from Vercel into `.env.local`, matching how this
// project already handles local secrets, e.g. SITE_URL). Loading `.env.local`
// explicitly keeps Prisma CLI commands and the running Next.js app pointed at
// the same real database.
config({ path: ".env.local" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
